apiVersion: v1
kind: Pod
metadata:
  name: file-copy-pod
  labels:
    name: file-copy-pod
spec:
  containers:
  - name: file-copy-container
    image: busybox
    command:
      - "sh"
      - "-c"
      - "chmod -R 777 /data && sleep 3000" # Keep pod running until file operation completes
    volumeMounts:
      - name: local-storage
        mountPath: /data
    securityContext:
      runAsUser: 0 # Run as root user
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: local-storage
      persistentVolumeClaim:
        claimName: local-pvc
  restartPolicy: Never
